databases:
  - name: book_management_server
    databaseName: book_management_server
    user: book_management_server

services:
  - type: web
    name: book_management_server
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: book_management_server
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false